### ISSUE TITLE
column output in regions.tsv

### ISSUE THREAD

**Issue by cflsjt** [vladsaveliev/TargQC#4]
Hi I am using your tool and it seems really useful. However I am having issues trusting that I'm looking at the right thing in the output files. I am looking through the regions.tsv file to get an idea of avg depth across a bait region in each of my samples. I'm using awk to select columns with useful information but I'm finding it very difficult to match up the contents of the regions file with the header that is generated. 

```
#Sample	Chr	Start	End	Size	Gene	Exon	Strand	Feature	Biotype	Transcript	Tx overlap	Exome overlap	Min depth	Avg depth	Median depth	Std dev	W/n 20% of median	1x	5x	10x	20x	50x	100x	250x	500x	1000x	5000x	10000x	50000x
PFR_100904_P01_WA07_PS1.1.68.5_bwaMEM.RG	CHR1	8673	8794	121	Acc00002.1	23	17.3388	100	100	100	0%	0%	.	17.3388	.	.	.	100	100	100	0	0	0	0	0	0	0	0	0
```
The column separation is unclear and I can't understand it to be honest.
I am assuming the value of 17.3388 is Avg depth but I can't be sure because I can't seem to rationalise the column values. Maybe you can explain this or add some information on the output files in your README?

Thanks

Susan

**Comment by vladsaveliev** [comment]
Hi Susan,

Thanks a lot for a good question, that's a fair point. I'll take a look at it now and clean up and document the columns,

Vlad

**Comment by vladsaveliev** [comment]
Susan,

I updated README with some output explanations: https://github.com/vladsaveliev/TargQC#output
I also put a tool `tsv` that you can use to view a tab-separated file in a nice column view from command line:

```
tsv regions.tsv
chr    start     end       size  gene          exon
chr21  9825763   9825854   91    .             .
chr21  9825861   9826312   451   .             .
chr21  9907173   9907501   328   TEKT4P2       3
```

You can first awk the file before passing to tsv:

```
cat regions.tsv | awk -F'\t' '{OFS="\t"} { print $1, $2, $3, $5, $14 }' | tsv
chr    start     end       size  gene          exon
chr21  9825763   9825854   91    .             .
chr21  9825861   9826312   451   .             .
chr21  9907173   9907501   328   TEKT4P2       3
```

However I recommend installing [bioawk](https://github.com/lh3/bioawk) (can do with `conda install -c bioconda bioawk`) and using it to select columns by name - I specifically altered columns names to better work with bioawk.

```
cat regions.tsv | bioawk -tc hdr '{ print $chr, $start, $end, $gene, $avg_depth, $at100x }' | tsv
chr    start     end       gene        avg_depth  at100x
chr21  9907173   9907501   TEKT4P2     115.137    66.7683
chr21  10863011  10863111  IGHV1OR21-1 106.93     100    
chr21  10910285  10910401  TPTE        36.3621    0      
```

You can update TargQC from conda:

```
conda install -c vladsaveliev targqc=1.8
```

Or from source by pulling and running `pip install .`

```
cd TargQC
git pull
pip install .
```

Hope this helps!
