### ISSUE TITLE
Critical Error on running targqc 

### ISSUE THREAD

**Issue by Vithyanatarajan** [vladsaveliev/TargQC#5]
Error message obtained:
------------------------------
targqc.utilz.logger.CriticalError: Error: "qualimap" executable is not found in PATH

Command used 
--------------------
targqc ~/Documents/sample.bam
Plz help me to resolve the issue

**Comment by vladsaveliev** [comment]
Hi,

Have you installed the tool with [conda](https://conda.io/miniconda.html)?

```
conda install -c vladsaveliev targqc
```

**Comment by NVithya** [comment]
Hi @vladsaveliev 
      I have installed using the source link

**Comment by vladsaveliev** [comment]
Ah, I see. Installation from source assumed that you had dependencies like `qualimap`, `sambamba`, `bedtools` already installed on your system. Sorry, that's my fault, should have stated it in the docs.

Can you try installing it from conda by any chance? Should be quicker and easier.

Linux:

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
```

macos:

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
```

Then on all systems:

```
bash miniconda.sh -b -p ./miniconda
unset PYTHONPATH
export PATH=$(pwd)/miniconda/bin:$PATH
conda install -y -c vladsaveliev -c bioconda -c conda-forge targqc
```

Conda is great and have tons of bioinformatics packages hosted by [bioconda](https://bioconda.github.io). Totally recommend to use it to install other packages too.

Hope it helps,
Vlad

**Comment by NVithya** [comment]
hi @vladsaveliev 
        I followed installation steps as you said .Even then I am getting the same error.

> targqc.utilz.logger.CriticalError: Error: "qualimap" executable is not found in PATH

**Comment by NVithya** [comment]
Command used for installing the qualimap  and similarly for bedtools and sambamba
-------------------------------------------------
conda install -y -c vladsaveliev -c bioconda -c conda-forge qualimap
Solving environment: done

# All requested packages already installed.

**Comment by vladsaveliev** [comment]
Can you try activating the base environement and then try running `targqc` again?

```
conda activate base
```

**Comment by vladsaveliev** [comment]
I added this line later, realizing it would work outside of a conda environment. The `base` environment is the default one, base you still need to activate it.

**Comment by NVithya** [comment]
Thank u so much  @vladsaveliev 
          Qualimap ran successfully,without any error.But I am now getting two new issues. Can u please look into that help in resolving those issues.

1.   /home/vithya/anaconda2/bin/sambamba: error while loading shared libraries: libphobos2-ldc-shared.so.81: cannot open shared object file: No such file or directory
2. subprocess.CalledProcessError: Command 'set -o pipefail; /home/vithya/anaconda2/bin/sambamba view -c -F "not unmapped and not duplicate" /home/vithya/coverage_testing/TargQC/work/Santhi_fastq/Santhi_fastq.sorted.bam > /home/vithya/coverage_testing/TargQC/work/Santhi_fastq/Santhi_fastq.sorted.bam_num_not_unmapped_and_not_duplicate.tx' returned non-zero exit status 127

**Comment by vladsaveliev** [comment]
Looks like it's the new sambamba version issue, these guys have the same error: https://github.com/bioconda/bioconda-recipes/issues/11422
Can you try the proposed solution and rerun?

```
conda install -c conda-forge ldc=1.11.0 
```

If that works, I will pin ldc=1.11.0 in targqc environment so it works out of the box.

**Comment by vladsaveliev** [comment]
That command actually doesn't work for me and conflicts with `pybedtools` :) 

If that doesn't work for you either, try downgrading sambamba?

```
conda install -c bioconda sambamba=0.6.6
```

**Comment by NVithya** [comment]
Hi @vladsaveliev 
               I again followed the above steps suggested by you, it worked fine. And sambamba error also got fixed. Thank you.
                   And again I am facing a small issue. Please look into it and help me in resolving it.

Error Message:
    assert percent_usable <= 1.0 or percent_usable is None, str(percent_usable)
AssertionError: 1.00009990103

**Comment by vladsaveliev** [comment]
Hey, just fixed that. Can you update with?

```
conda install -y -c vladsaveliev -c bioconda -c conda-forge targqc==1.8.1
```

**Comment by NVithya** [comment]
Hi @vladsaveliev 
            Thank you so much for your help and support. I can now run my analysis without any issues.Now got my results .

**Comment by NVithya** [comment]
@vladsaveliev  One Question is there any possibility to show gene-based coverage instead of each exon coverage of each gene

**Comment by NVithya** [comment]
@vladsaveliev One question is there any possibility to get gene-based coverage instead of each exon-based coverage of each gene.
Like one to one relationship A gene and its coverage.

Thanks

**Comment by vladsaveliev** [comment]
Glad it worked!

> @vladsaveliev One Question is there any possibility to show gene-based coverage instead of each exon coverage of each gene

You can grep transcript features with `grep -w transcript regions.tsv`

**Comment by Vithyanatarajan** [comment]
I want the coverage for 1000 genes like a format as shown below. Because currently m getting the coverage for each exon (separately) of a single gene. But I require the Coverage information for the complete one gene. 

Sl.no Gene at1X
1. ALK         50
2. BRAF       96
3. EGFR       86

**Comment by vladsaveliev** [comment]
@Vithyanatarajan, can you send me the `regions.tsv` file you are getting? It supposed to have coverage for entire genes (=transcripts) in addition to per-exon coverage. So if you run `grep -w transcript regions.tsv | cut -f6,15  | tsv`, that should give you exactly what you seek.

**Comment by Vithyanatarajan** [comment]
Hi @vladsaveliev 
             Thank you for the suggestion and help. I got my desired result.

with regards
Vithya

**Comment by vladsaveliev** [comment]
Glad it worked!
